name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello,World!"
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: echo "Good Bye"
