name: CI
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App Name to be modified"
        required: true
      icon_path:
        description: "Downloadable URL to the IconKitchen-Output.zip file"
        required: true

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'gradle'

      - name: Download IconKitchen-Output.zip and Copy Icons
        run: |
            wget -O IconKitchen-Output.zip ${{ github.event.inputs.icon_path }}
            unzip IconKitchen-Output.zip -d temp_unzip
            cp -r temp_unzip/android/res/* app/src/main/res/
            cp temp_unzip/android/play_store_512.png app/src/main/ic_launcher-playstore.png
            rm -rf temp_unzip IconKitchen-Output.zip
        shell: bash

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Customize App
        run: ./gradlew customizeApp -Papp_name="${{ github.event.inputs.app_name }}"

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
            name: app-debug
            path: app/build/outputs/apk/debug/app-debug.apk
