name: CI
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App Name to be modified"
        required: true
      icon_path:
        description: "Downloadable URL to the IconKitchen-Output.zip file"
        required: true

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'gradle'

      - name: Download IconKitchen-Output.zip and Copy Icons
        run: |
            wget -O IconKitchen-Output.zip ${{ github.event.inputs.icon_path }}
        shell: bash
      - name : Unzip IconKitchen-Output.zip
        run: |
          @echo off
          setlocal enabledelayedexpansion
          
          set ZIP_PATH=IconKitchen-Output.zip
          set ANDROID_PROJECT_PATH=app\src\main\res
          
          :: Generate a unique temporary directory name in the system's temp directory
          :generate_temp_dir
          set "TEMP_DIR=%TEMP%\copy_resources_temp_%random%"
          if exist "!TEMP_DIR!" (
              goto generate_temp_dir
          )
          
          :: Create the temporary directory
          mkdir "!TEMP_DIR!"
          
          :: Unzip the contents of the ZIP archive to the temporary directory
          powershell -Command "Expand-Archive -Path '%ZIP_PATH%' -DestinationPath '!TEMP_DIR!'"
          
          :: Loop through subdirectories in the temporary directory and move their contents to the ANDROID_PROJECT_PATH
          for /d %%d in ("!TEMP_DIR!\android\res\*") do (
              set "subdir=%%~nxd"
              xcopy /s /y "%%d\*" "%ANDROID_PROJECT_PATH%\!subdir!\"
          )
          
          :: Copy play-store-512.png to app/src/main and rename it to ic_launcher-playstore.png
          copy "!TEMP_DIR!\android\play_store_512.png" "app\src\main\ic_launcher-playstore.png"
          
          :: Remove the temporary directory
          rmdir /s /q "!TEMP_DIR!"
          
          echo Files copied successfully
        shell: cmd

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Customize App
        run: ./gradlew customizeApp -Papp_name="${{ github.event.inputs.app_name }}"

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
            name: app-debug
            path: app/build/outputs/apk/debug/app-debug.apk
